#!/usr/bin/env sh

cp ~/repos/dotfiles/zsh/zshrc ~/.zshrc

cp ~/repos/dotfiles/vim/vimrc ~/.vimrc

cp ~/repos/dotfiles/git/gitconfig ~/.gitconfig
cp ~/repos/dotfiles/git/gitignore_global ~/.gitignore_global

cp ~/repos/dotfiles/.claude/statusline.py ~/.claude/
cp -r ~/repos/dotfiles/.claude/skills/* ~/.claude/skills/
