export ZSH="/Users/wiebe/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
git
macos
docker
vagrant-prompt
vagrant
zsh-autosuggestions
zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

export PATH="~/bin:~/.local/bin:$PATH"
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
